// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Progetto_BE_S5L5.Data;

#nullable disable

namespace Progetto_BE_S5L5.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250314085205_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Progetto_BE_S5L5.Models.Anagrafica", b =>
                {
                    b.Property<Guid>("Idanagrafica")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idanagrafica");

                    b.Property<int>("Cap")
                        .HasColumnType("int");

                    b.Property<string>("Citta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("Codice_Fiscale");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Idanagrafica")
                        .HasName("PK__Anagrafi__7AB1023C929CB4F0");

                    b.HasIndex(new[] { "CodiceFiscale" }, "Unique_CF")
                        .IsUnique();

                    b.ToTable("Anagrafica");
                });

            modelBuilder.Entity("Progetto_BE_S5L5.Models.Verbale", b =>
                {
                    b.Property<Guid>("IdVerbale")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idVerbale");

                    b.Property<DateOnly>("DataTrascrizioneVerbale")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataViolazione")
                        .HasColumnType("date");

                    b.Property<int>("DecurtamentoPunti")
                        .HasColumnType("int");

                    b.Property<Guid>("Idanagrafica")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idanagrafica");

                    b.Property<Guid>("Idviolazione")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idviolazione");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(9, 2)");

                    b.Property<string>("IndirizzoViolazione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NominativoAgente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdVerbale")
                        .HasName("PK__Verbale__A0FAF4534A6E58E3");

                    b.HasIndex("Idanagrafica");

                    b.HasIndex("Idviolazione");

                    b.ToTable("Verbale");
                });

            modelBuilder.Entity("Progetto_BE_S5L5.Models.Violazione", b =>
                {
                    b.Property<Guid>("Idviolazione")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idviolazione");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Idviolazione")
                        .HasName("PK__Violazio__AF77BD923F484CD4");

                    b.ToTable("Violazione");
                });

            modelBuilder.Entity("Progetto_BE_S5L5.Models.Verbale", b =>
                {
                    b.HasOne("Progetto_BE_S5L5.Models.Anagrafica", "IdanagraficaNavigation")
                        .WithMany("Verbales")
                        .HasForeignKey("Idanagrafica")
                        .IsRequired()
                        .HasConstraintName("Fk_Anagrafica_Verbale");

                    b.HasOne("Progetto_BE_S5L5.Models.Violazione", "IdviolazioneNavigation")
                        .WithMany("Verbales")
                        .HasForeignKey("Idviolazione")
                        .IsRequired()
                        .HasConstraintName("Fk_Violazione_Verbale");

                    b.Navigation("IdanagraficaNavigation");

                    b.Navigation("IdviolazioneNavigation");
                });

            modelBuilder.Entity("Progetto_BE_S5L5.Models.Anagrafica", b =>
                {
                    b.Navigation("Verbales");
                });

            modelBuilder.Entity("Progetto_BE_S5L5.Models.Violazione", b =>
                {
                    b.Navigation("Verbales");
                });
#pragma warning restore 612, 618
        }
    }
}
